[package]
name = "braid-triggerbox-comms"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.82"
description = "host and device communication for Braid triggerbox"
repository = "https://github.com/strawlab/triggerbox"
homepage = "https://github.com/strawlab/triggerbox/tree/main/braid-triggerbox-rs/braid-triggerbox-comms"

[dependencies]
defmt = { version = "1.0.1", optional = true }
log = { version = "0.4.34", optional = true }
fugit = "0.6.0"

[features]
default = ["std"]

std = ["log"]
defmt = ["dep:defmt", "fugit/defmt"]
