# Choose a default "cargo run" tool. (See "Alternative runners" in the README.)
# probe-rs is recommended if you have a debug probe
# elf2uf2-rs loads firmware over USB mass storage when the rp2040 is in boot mode
# (this hangs on recent macOS, so we use picotool, which talks to the PICOBOOT
# USB interface directly)
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "probe-rs run --chip RP2040"
# runner = "elf2uf2-rs -d"
runner = "picotool load -u -v -x -t elf"

rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",

  # Code-size optimizations.
  #   trap unreachable can save a lot of space, but requires nightly compiler.
  #   uncomment the next line if you wish to enable it
  # "-Z", "trap-unreachable=no",
  "-C", "no-vectorize-loops",
]

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"
