[package]
name = "braid-triggerbox"
version = "0.4.2"
authors = ["Andrew Straw <strawman@astraw.com>"]
license = "MIT OR Apache-2.0"
description = "camera synchronization trigger box for Braid"
repository = "https://github.com/strawlab/triggerbox"
homepage = "https://github.com/strawlab/triggerbox/tree/main/braid-triggerbox-rs"
edition = "2021"
rust-version = "1.89"

[dependencies]
thiserror = "2"
anyhow = "1.0.104"
tokio = { version = "1.53", default-features = false, features = [
    "sync",
    "macros",
    "time",
    "io-util",
    "rt-multi-thread",
] }
tokio-serial = "5.5.0"
log = "0.4.34"
byteorder = "1.5"
serde = "1.0.229"
nalgebra = "0.35"
chrono = { version = "0.4.45", default-features = false, features = [
    "clock",
    "std",
    "wasmbind",
] }
lstsq = "0.8.0"
env_logger = "0.11.11"
crc = "3.4"
clap = { version = "4.6", features = ["derive"] }

braid-triggerbox-comms = { version = "0.1", path = "braid-triggerbox-comms" }

[workspace]
members = ["braid-triggerbox-comms"]
