#!/usr/bin/env python
import time
import argparse

import roslib; roslib.load_manifest('triggerbox')

import rospy
from triggerbox.triggerbox_client import TriggerboxClient

if __name__=='__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--set-framerate', type=float, default=None,
                        help='set framerate')
    parser.add_argument('--synchronize', action='store_true', default=False,
                        help='synchronize')
    parser.add_argument('--set-aout-volts', type=str, default=None,
                        help='set AOUT0, AOUT1 in Volts')
    parser.add_argument('--set-aout-raw', type=str, default=None,
                        help='set AOUT0, AOUT1 in raw DAC units')

    rospy.init_node('triggerbox_client')
    argv = rospy.myargv()
    args = parser.parse_args(argv[1:])

    DEFAULT_HOST_NODE = '/triggerbox_host'
    host_node = rospy.resolve_name(DEFAULT_HOST_NODE)
    if host_node == DEFAULT_HOST_NODE:
        rospy.logwarn('using default name %r'%host_node)
    else:
        rospy.loginfo('using name %r'%host_node)

    trig = TriggerboxClient(host_node=host_node)

    if args.set_framerate is not None:
        trig.set_frames_per_second_blocking(args.set_framerate)

    if args.synchronize:
        trig.synchronize()

    if args.set_aout_volts is not None:
        buf = args.set_aout_volts

        # parse buf into two floats
        buf = buf.split(',')
        buf = [ b.strip().split() for b in buf ]
        bufs = []
        for b in buf:
            bufs.extend(b)
        aout0, aout1 = map(float, bufs)

        trig.set_aout_ab_volts(aout0,aout1)

    if args.set_aout_raw is not None:
        buf = args.set_aout_raw

        # parse buf into two ints
        buf = buf.split(',')
        buf = [ b.strip().split() for b in buf ]
        bufs = []
        for b in buf:
            bufs.extend(b)
        aout0, aout1 = map(int, bufs)

        trig.set_aout_ab_raw(aout0,aout1)
    time.sleep(0.5)
