#!/usr/bin/env python
import argparse

import roslib; roslib.load_manifest('triggerbox')

import rospy
from triggerbox.triggerbox_host import TriggerboxHost

if __name__=='__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--device', type=str, default=None,
                        required=True,
                        help='specify the USB device (e.g. "/dev/ttyACM0")')

    argv = rospy.myargv()
    args = parser.parse_args(argv[1:])

    rospy.init_node('triggerbox_host')
    tb = TriggerboxHost(device=args.device)

    fr = rospy.get_param('~frames_per_second', -1.0)
    if fr != -1.0:
        tb.set_frames_per_second_blocking(fr)

    rospy.spin()

