[package]
name = "t2comms"
version = "0.1.0"
edition = "2021"
rust-version = "1.58"

[dependencies]
bbqueue = "0.5.1"
defmt = "0.3.0"

[features]
default = ["std"]

std = []
thumbv6 = ["bbqueue/thumbv6"]
