#!/usr/bin/env python
import argparse
import time
import sys

import roslib
roslib.load_manifest('triggerbox')

import rospy
from triggerbox.triggerbox_device import TriggerboxDevice

class WaitForConnected(TriggerboxDevice):

    def __init__(self, device, name):
        TriggerboxDevice.__init__(self, device, name, name)

    def _notify_fatal_error(self, msg):
        print "ERROR: %s" % msg
        sys.exit(1)

    def _notify_connected(self, name, device):
        print "SET NAME: connected to '%s' via %s" % (name, device)
        sys.exit(0)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--device', type=str, default='/dev/ttyUSB0',
                        help='usb port')
    parser.add_argument('name', type=str, nargs=1,
                        help='name (e.g. trig1)')

    argv = rospy.myargv()
    args = parser.parse_args(argv[1:])

    d = WaitForConnected(args.device, args.name[0])
    d.join()
